apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  db_name: {{ .Values.db.name | b64enc | quote  }}
  db_user: {{ .Values.db.user | b64enc | quote  }}
  db_pass: {{ .Values.db.pass | b64enc | quote  }}
  db_host: {{ .Values.db.host | b64enc | quote  }}
  db_driver: {{ .Values.db.driver | b64enc | quote  }}
  db_port: {{ .Values.db.port | b64enc | quote  }}
  fec_key: {{ .Values.fec_key | b64enc | quote  }}
